version: '3'
services:
  python:
    build: .
    volumes:
      - '.:/products'

    tty: true
    stdin_open: true

    ports:
      - 8000:8000

    env_file:
      - .env

    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCOUNT_KEY: ${AWS_ACCOUNT_KEY}
      AWS_ACCOUNT_SECRET: ${AWS_ACCOUNT_SECRET}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      GOOGLE_CSE_ID: ${GOOGLE_CSE_ID}
      SERPAPI_API_KEY: ${SERPAPI_API_KEY}
      CHAT_TEMPLATE_PATH: ${CHAT_TEMPLATE_PATH}

    extra_hosts:
      - localhost:${DOCKER_HOST_IP}

