version: '3'
services:
  python:
    build: .
    volumes:
      - '.:/products'

    tty: true
    stdin_open: true

    ports:
      - 8000:8000

    env_file:
      - .env

    extra_hosts:
      - localhost:${DOCKER_HOST_IP}
