version: '3'

volumes:
  db-data:

services:
  python:
    build: .
    volumes:
      - '.:/products'

    tty: true
    stdin_open: true

    ports:
      - 8000:8000
    env_file:
      - .env
    extra_hosts:
      - localhost:${DOCKER_HOST_IP}
    
    depends_on:
      - db
    links:
      - db
  
  db:
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_HOST=${POSTGRES_HOST}'
      - 'POSTGRES_PORT=${POSTGRES_PORT}'
    
    extra_hosts:
      - localhost:${POSTGRES_HOST}

    image: postgres
    volumes:
      - 'db-data:/var/lib/postgresql/data'


